### ISSUE TITLE
can make it work via Xcode edit extension?

### ISSUE THREAD

**Issue by litt1e-p** [qfish/XAlign#92]
can make it work via Xcode edit extension?

**Comment by qfish** [comment]
Coming soon!

<img width="797" alt="screen shot 2016-11-04 at 12 58 17 am" src="https://cloud.githubusercontent.com/assets/679824/19976232/e131b4b6-a229-11e6-8986-43c34c184c16.png">

**Comment by qfish** [comment]
Xcode 8 is supported! Check https://github.com/qfish/XAlign#install-on-xcode-8

**Comment by litt1e-p** [comment]
[dmg](https://github.com/qfish/XAlign/releases/download/untagged-37425b5c3153fd315072/XAlign.1.0.dmg) page not found?

**Comment by srikanth-vm** [comment]
DMG link is broken .

**Comment by qfish** [comment]
My bad, it's ok now :)

**Comment by litt1e-p** [comment]
the `XAlign.app` can not found in XAlign.dmg....

**Comment by qfish** [comment]
The `XAlign.app` is in the DMG, but the problem is its position 😅. 

![mis](https://cloud.githubusercontent.com/assets/679824/20269489/3f55e408-aabe-11e6-8402-0bb408d8a5ac.gif)

Finally I have fixed it, thank you !

![d0c71645-5063-4cc4-e2a4-1f0eb731285d](https://cloud.githubusercontent.com/assets/679824/20269529/713506f2-aabe-11e6-9e14-ca8aaa1db55b.png)
